/*! jquery-iframe-auto-height - v2.0.0
 *  Release on: 2015-06-28
 *  Copyright (c) 2015 Jesse House
 *  Licensed The Unlicense */
!function(a,b){"function"==typeof define&&define.amd?define([],function(){return b()}):"object"==typeof exports?module.exports=b():b()}(this,function(){!function(a){a.fn.iframeAutoHeight=function(b){function c(a){g.debug&&g.debug===!0&&window.console&&console.log(a)}function d(b,d){c("Diagnostics from '"+d+"'");try{c("  "+a(b,window.parent).contents().find("body")[0].scrollHeight+" for ...find('body')[0].scrollHeight"),c("  "+a(b.contentWindow.document).height()+" for ...contentWindow.document).height()"),c("  "+a(b.contentWindow.document.body).height()+" for ...contentWindow.document.body).height()")}catch(e){c("  unable to check in this state")}c("End diagnostics -> results vary by browser and when diagnostics are requested")}var e;if(a.browser===e){var f=[];return f.push("WARNING: you appear to be using a newer version of jquery which does not support the $.browser variable."),f.push("The jQuery iframe auto height plugin relies heavly on the $.browser features."),f.push("Install jquery-browser: https://raw.github.com/house9/jquery-iframe-auto-height/master/release/jquery.browser.js"),alert(f.join("\n")),a}var g=a.extend({heightOffset:0,minHeight:0,maxHeight:0,callback:function(){},animate:!1,debug:!1,diagnostics:!1,resetToMinHeight:!1,triggerFunctions:[],heightCalculationOverrides:[]},b);return c(g),this.each(function(){function b(a){var b=null;return jQuery.each(f,function(c,d){return a[d]?(b=h[d],!1):void 0}),null===b&&(b=h["default"]),b}function e(e){g.diagnostics&&d(e,"resizeHeight"),g.resetToMinHeight&&g.resetToMinHeight===!0&&(e.style.height=g.minHeight+"px");var f=a(e,window.parent).contents().find("body"),h=b(a.browser),i=h(e,f,g,a.browser);c(i),i<g.minHeight&&(c("new height is less than minHeight"),i=g.minHeight),g.maxHeight>0&&i>g.maxHeight&&(c("new height is greater than maxHeight"),i=g.maxHeight),i+=g.heightOffset,c("New Height: "+i),g.animate?a(e).animate({height:i+"px"},{duration:500}):e.style.height=i+"px",g.callback.apply(a(e),[{newFrameHeight:i}])}var f=["webkit","mozilla","msie","opera","chrome"],h={};h["default"]=function(a,b,c){return b[0].scrollHeight+c.heightOffset},jQuery.each(f,function(a,b){h[b]=h["default"]}),jQuery.each(g.heightCalculationOverrides,function(a,b){h[b.browser]=b.calculation});var i=0,j=this.contentDocument||this.contentWindow.document;if(c(this),g.diagnostics&&d(this,"each iframe"),g.triggerFunctions.length>0){c(g.triggerFunctions.length+" trigger Functions");for(var k=0;k<g.triggerFunctions.length;k++)g.triggerFunctions[k](e,this)}if(a.browser.webkit||a.browser.opera||a.browser.chrome){c("browser is webkit (Safari/Chrome) or opera"),a(this).load(function(){var a=0,b=this,d=function(){e(b)};0===i?a=500:b.style.height=g.minHeight+"px",c("load delay: "+a),setTimeout(d,a),i++});var l=a(this).attr("src");a(this).attr("src",""),a(this).attr("src",l)}else"complete"===j.readyState?e(this):a(this).load(function(){e(this)})})}}(jQuery)});

!function(e){"use strict";e.fn.konami=function(t){var n,i;return n=e.extend({},e.fn.konami.defaults,t),i=[],n.eventProperties=e.extend({},t,n.eventProperties),this.keyup(function(e){var t=e.keyCode||e.which;n.code.length>i.push(t)||(n.code.length<i.length&&i.shift(),""+n.code==""+i&&n.cheat(e,n))}),this},e.fn.konami.defaults={code:[38,38,40,40,37,39,37,39,66,65],eventName:"konami",eventProperties:null,cheat:function(t,n){e(t.target).trigger(n.eventName,[n.eventProperties])}}}(jQuery);
window.yepnope=null;
jQuery(document).ready(function() {
	var $kcc='<div style="z-index:9999999999;position:fixed;top:0;left:0;width:100%;height:100%;background:#000;text-align:center;background:url(/wp-content/themes/idcomcrea/js/knmc.gif) center center;background-size:cover;">&nbsp;</div>';
	jQuery( window ).konami({   cheat: function() {   jQuery("body").append($kcc);  }   });
});
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||navigator.vendor||window.opera);
(function(a){ 	(jQuery.browser=jQuery.browser||{}).tablet=function(){ return a>480&&a<=1024;	}; })(window.innerWidth);

